version: '3'

volumes:
  mysqldata:

services:
  phpserver:
    build: ./php
    volumes:
      - ./:/var/www/

  mysqlserver:
    image: mysql
    environment:
      MYSQL_DATABASE: dockerfordevs
      MYSQL_ROOT_PASSWORD: docker
    volumes:
      - mysqldata:/var/lib/mysql

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
